### ISSUE TITLE
Latest k2pdfopt is 2.33a

### ISSUE THREAD

**Issue by timofonic** [koreader/libk2pdfopt#26]
Hello.

Latest k2pdfopt is 2.33a. You can see it in the website.
http://www.willus.com/k2pdfopt/

Anyway, I sent a forum message.

Does the developer uses Git? Maybe if he uses it, k2pdfopt deployment could be easier :)

http://www.mobileread.com/forums/showthread.php?p=3235510#post3235510

**Comment by chrox** [comment]
Already catched up with the latest k2pdfopt.
