### ISSUE TITLE
Remove some printf?

### ISSUE THREAD

**Issue by poire-z** [koreader/libk2pdfopt#34]
Any reason to keep these 2 printf, which output some stuff every page turn in our crash.log?

https://github.com/koreader/libk2pdfopt/blob/d5405c89a086fcb800d53a9f81ac9ba446378b12/koptcrop.c#L66-L67

**Comment by houqp** [comment]
Looks like debug print to me, we should remove it or make it a no op in none-debug mode.

**Comment by Frenzie** [comment]
Agreed, a debug ifdef should do the trick.
