### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by cvanelteren** [koreader/libk2pdfopt#37]
Hi could you provide build instructions?

`cmake .` failes with

```
-- Configuring done
CMake Error at willuslib/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    ocrjocr.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at willuslib/CMakeLists.txt:27 (add_library):
  No SOURCES given to target: willuslib
```

I don't see the required file in the source.

**Comment by cvanelteren** [comment]
leaving that file out gives another error in `k2master.c` where `ocr_max_columns` is not found. Changing that to `max_columns` leaves clean build.

**Comment by Frenzie** [comment]
I imagine the CMake file should work if you follow the instructions in [readme_k2src.txt](https://github.com/koreader/libk2pdfopt/blob/f28a9afc58dccabcc34b3dc21f9aa101c10aa9f6/readme_k2src.txt) but we use the Makefile. See [here](https://github.com/koreader/koreader-base/blob/4a91eefe3a42f926ebe262658c258c9929544836/thirdparty/libk2pdfopt/CMakeLists.txt).

**Comment by cvanelteren** [comment]
Ok will have a look thanks!
